<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Silk.NET.Input.Sdl" Version="2.23.0" />
      <PackageReference Include="Silk.NET.SDL" Version="2.23.0" />
      <PackageReference Include="Silk.NET.Windowing.Sdl" Version="2.23.0" />
    </ItemGroup>
<ItemGroup>
    <Compile Remove="Blackjack.Tests\**" />
    <EmbeddedResource Remove="Blackjack.Tests\**" />
    <None Remove="Blackjack.Tests\**" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Assets\cards.bmp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
